# Generated by Django 5.2.11 on 2026-02-19 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="MONNIFY", max_length=20)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="virtualaccount",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="virtualaccount",
            name="provider_ref",
        ),
        migrations.AddField(
            model_name="paymentwebhookevent",
            name="processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="account_reference",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="monnify_account_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="provider",
            field=models.CharField(
                choices=[("MONNIFY", "Monnify")], default="MONNIFY", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="reserved_account_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="account_name",
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name="virtualaccount",
            name="bank_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name="virtualaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "account_reference", "account_number"),
                name="uniq_provider_account_ref_number",
            ),
        ),
        migrations.AddField(
            model_name="incomingpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
