# Generated by Django 5.2.11 on 2026-02-19 09:49

import apps.vtu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vtu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="ledger_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="provider_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="reference",
            field=models.CharField(
                default=apps.vtu.models.generate_order_reference,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="service_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
