# Generated by Django 5.2.11 on 2026-02-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vtu", "0002_purchaseorder_ledger_reference_purchaseorder_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBundlePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(max_length=30)),
                ("plan_code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_plans",
                        to="vtu.serviceprovider",
                    ),
                ),
            ],
        ),
    ]
